version: '3.2'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
#    volumes:
#      - postgres:/var/lib/postgresql/data
#volumes:
#  postgres:
